emp_reg/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='emp_reg'

urlpatterns = [

    path('list/', views.employee_list, name='emp_list'),
    path('<int:id>/', views.employee_form, name='emp_update'),
    path('delete/<int:id>/', views.employee_delete, name='emp_delete'),
    path('', views.employee_form, name='emp_insert'),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('emp_reg.urls', namespace='emp_reg')),
]

emp_reg/models.py
from django.db import models

class Position(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

class Employee(models.Model):
    fullname = models.CharField(max_length=100)
    emp_code = models.CharField(max_length=3)
    mobile = models.CharField(max_length=15)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)


    def __str__(self):
        return self.fullname

emp_reg/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee  
        fields = ('fullname','mobile', 'emp_code', 'position')
        labels = {

            'fullname': 'Full name',
            'emp_code': 'EMP. Code'
        }

    def __init__(self, *args, **kwargs):
        super(EmployeeForm, self).__init__(*args, **kwargs)
        self.fields['position'].empty_label='Select'
        self.fields['emp_code'].required=False

emp_reg/views.py
from django.shortcuts import render, redirect
from .forms import EmployeeForm
from .models import Employee

def employee_list(request):

    context = {'emp_list': Employee.objects.all()}
    return render(request, 'emp_reg/employee_list.html', context)

def employee_form(request, id=0):
    if request.method == 'GET':
        if id==0:
            form = EmployeeForm()
        else:
            employee = Employee.objects.get(pk=id)
            form = EmployeeForm(instance=employee)
        
        context = {'form': form}
        return render(request, 'emp_reg/employee_form.html', context)
    else:
        if id==0:
            form = EmployeeForm(request.POST)
        else: 
            employee = Employee.objects.get(pk=id)
            form = EmployeeForm(request.POST,instance=employee)
        if form.is_valid:
            form.save()
        return redirect('emp_reg:emp_list')

def employee_delete(request, id):
    employee = Employee.objects.get(pk=id)
    employee.delete()
    return redirect('emp_reg:emp_list')
    

templates/emp_reg/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Employee Register</title>
</head>
<body>

    <div class="container">
        <div class="col-md-10 offset-md-1 mt-5">
            <div class="jumbotron">
                <h1 class="display-4">Employee register</h1>
                <p class="lead font-italic">Python Django project for implementing CRUD operations</p>
                <hr class="my-4">
                {% block content %}
                {% endblock content %}
              </div>

        </div>
    </div>
    

    <!-- #region SCRIPTS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <!-- #endregion SCRIPTS -->
    
</body>
</html>

templates/emp_reg/employee_form.html
{% extends 'emp_reg/base.html' %}
{% load crispy_forms_tags %}

{% block content %}


<form method="post" autocomplete="off">

    {% csrf_token %}
    {{form.fullname|as_crispy_field}}
    {{form.mobile|as_crispy_field}}
    <div class="row">
        <div class="col-md-4">
            {{form.emp_code|as_crispy_field}}

        </div>
        <div class="col-md-8">
            {{form.position|as_crispy_field}}
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
        <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database"></i>&nbsp;Submit</button>

        </div>
        <div class="col-md-4">
            <a href="{% url 'emp_reg:emp_list' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i>&nbsp; Back to list
            </a>
        </div>
    </div>

</form>
{% endblock content %}
    

templates/emp_reg/employee_list.html
{% extends 'emp_reg/base.html' %}


{% block content %}

<table class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Full Name</td>
            <td>Mobile</td>
            <td>Position</td>
            <td>
                <a href="{% url 'emp_reg:emp_insert' %}" class="btn btn-outline-success">
                    <i class="fas fa-plus"></i> Add new
                </a>
                </a>
            </td>
        </tr>
    </thead>
    <tbody>
        {% for employee in emp_list %}
            <tr>
                <td>{{employee.fullname}}</td>
                <td>{{employee.mobile}}</td>
                <td>{{employee.position}}</td>
                <td>
                    <a href="{% url 'emp_reg:emp_update' employee.id %}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <form action="{% url 'emp_reg:emp_delete' employee.id %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn">
                            <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                        </button>
                    
                    </form>
                </td>
            </tr>

        {% endfor %}
    </tbody>
</table>


{% endblock content %}